[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_airdrop = "8BjdTzm1Q852B2FqJagx3aAqpmuTjF4hatTBn7uAXt7f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/k/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
