[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_airdrop = "c1yG6B2Ch8SWuwKmAToWK8oKiUkPVeVhVLNgAEoSDTs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://tame-sleek-patina.solana-mainnet.quiknode.pro/1cc6139dba03cdaeb791b047274937ae3acc53a9/"
#cluster  = "mainnet"
wallet = "deploy-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
